Fix building for 83xx boards with USB support
Commit 29c6fbe0471afd7ffa41fcb2103eec5b53294897 broke
building for 83xx boards with USB support:

ehci-fsl.c: In function 'ehci_hcd_init':
ehci-fsl.c:43: error: 'CONFIG_SYS_FSL_USB_ADDR' undeclared (first use in this function)
ehci-fsl.c:43: error: (Each undeclared identifier is reported only once
ehci-fsl.c:43: error: for each function it appears in.)
make[1]: *** [ehci-fsl.o] Error 1

Signed-off-by: Anatolij Gustschin <agust@denx.de>