ARMv7: u8500_href: Add missing header to fix compiler warning
Fix the compiler warning

u8500_href.c: In function 'hrefplus_mmc_power_init':
u8500_href.c:258: warning: implicit declaration of function 'prcmu_i2c_read'
u8500_href.c:265: warning: implicit declaration of function 'prcmu_i2c_write'

by adding the missing header file.

Signed-off-by: Dirk Behme <dirk.behme@googlemail.com>