imx: remove unused 8mn evk dtsi
Otherwise throwing a build error with recent toolchains. For some
reasons the dtsi was somehow included, throwing:
  DTC     arch/arm/dts/imx8mn-ddr4-evk.dtb
Error: arch/arm/dts/.imx8mn-ddr4-evk.dtb.pre.tmp:222.1-10 syntax error
FATAL ERROR: Unable to parse input tree

Signed-off-by: Gary Bisson <gary.bisson@boundarydevices.com>